### ISSUE TITLE
released a new shadcn CLI. 

### ISSUE THREAD

**Issue by Zoot01** [Tobbe/setup-rwgc#4]
Good morning, 

shadcn released a new CLI that is breaking your CLI. Please see the shadcn changelog for details. 

https://ui.shadcn.com/docs/changelog

**Comment by Tobbe** [comment]
Thanks for the heads-up! I'll take a look

**Comment by Tobbe** [comment]
I've pinned the shad cli to the last compatible version for now. Will come back later to make sure we're compatible with the latest update
